version: '3'
services:

  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_IP}:${NGINX_PORT}:80
    volumes:
      - ./config/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/data
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: ./
      dockerfile: config/docker/php/dockerfile
    volumes:
      - ~/.ssh:/root/.ssh
      - .:/data
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: percona:5.7
    ports:
      - ${MYSQL_PORT}:3306
    tty: true
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    hostname: mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
